mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView
from .views import signup, custom_login, custom_logout, policy

urlpatterns = [
    path('qa_rpg/', include('qa_rpg.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='qa_rpg/')), 
    path("__reload__/", include("django_browser_reload.urls")),
    path('accounts/logout/', custom_logout, name='logout'),
    path('accounts/signup/', signup, name='signup'),
    path('accounts/login/', custom_login, name='login'),
    path('accounts/', include('allauth.urls')),
    path('policy/', policy, name='policy')
]

qa_rpg/urls.py
from django.urls import path

from . import views

app_name = 'qa_rpg'
urlpatterns = [
    path('index/', views.IndexView.as_view(), name='index'),
    path('template/', views.TemplateChooseView.as_view(), name='template'),
    path('template/choose', views.choose, name='choose'),
    path('template/summon/', views.SummonView.as_view(), name='summon'),
    path('template/summon/create', views.create, name='create'),
    path('dungeon/', views.DungeonView.as_view(), name='dungeon'),
    path('dungeon/report_previous', views.report_previous, name='report_previous'),
    path('dungeon/action', views.action, name='action'),
    path('dungeon/battle', views.BattleView.as_view(), name='battle'),
    path('dungeon/battle/item', views.item, name='item'),
    path('dungeon/battle/check/<int:question_id>', views.check, name='check'),
    path('dungeon/battle/run_away/<int:question_id>', views.run_away, name='run_away'),
    path('dungeon/treasure', views.TreasureView.as_view(), name='treasure'),
    path('dungeon/treasure/treasure_action', views.treasure_action, name='treasure_action'),
    path('shop/', views.ShopView.as_view(), name='shop'),
    path('shop/buy/', views.buy, name='buy'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/claim/<int:question_id>', views.claim_coin, name='claim'),
    path('profile/select_template', views.select, name='select'),
    path('profile/upgrade/', views.UpgradeView.as_view(), name='upgrade'),
    path('profile/upgrade/upgrade_action', views.upgrade, name='upgrade_action'),
    path('profile/upgrade/awake', views.awake, name='awake'),
    path('select/select_items', views.select_items, name='select_items'),
    path('select/', views.SelectItemsView.as_view(), name="select_dg"),
    path('', views.HomeView.as_view(), name='home')
]

qa_rpg/models.py
"""Module containing models for storing data in database."""
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser
from django_cryptography.fields import encrypt

BASE_LUCK = 0.25
BASE_HEALTH = 100


class User(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    first_name = encrypt(models.CharField(max_length=200))
    last_name = encrypt(models.CharField(max_length=200))
    policy = models.BooleanField(default=True)


class Question(models.Model):
    """Question model for creating questions."""

    question_text = models.CharField(max_length=200)
    damage = models.IntegerField(default=20)
    currency = models.IntegerField(default=0)
    max_currency = models.IntegerField(default=20)
    rate = models.IntegerField(default=5)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=100, null=False, default="test")
    enable = models.BooleanField(default=True)

    @property
    def report(self):
        """Get amount of reports this question has."""
        return ReportAndCommend.objects.filter(question=self, vote=0).count()

    @property
    def commend(self):
        """Get amount of commends this question has."""
        return ReportAndCommend.objects.filter(question=self, vote=1).count()

    @property
    def correct_choice(self):
        """Get the correct answer of this question."""
        return Choice.objects.get(question=self, correct_answer=True)

    def add_coin(self):
        """Add coins to question for owner to collect."""
        if self.currency + self.rate <= self.max_currency:
            self.currency += self.rate
            self.save()

    def __str__(self):
        """Return Question string."""
        return self.question_text


class Choice(models.Model):
    """Choice model for creating choices."""

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    correct_answer = models.BooleanField()

    def __str__(self):
        """Return Choice string."""
        return self.choice_text


class ReportAndCommend(models.Model):
    """Report and Commend model for creating reports or commends."""

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    vote = models.IntegerField()


class Player(models.Model):
    """Player model for creating players."""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    max_hp = models.IntegerField(default=BASE_HEALTH)
    current_hp = models.IntegerField(default=BASE_HEALTH)
    currency = models.IntegerField(default=0)
    dungeon_currency = models.IntegerField(default=0)
    activity = models.CharField(max_length=100, default="index")
    luck = models.FloatField(default=BASE_LUCK)
    awake = models.IntegerField(default=0)
    question_max_currency = models.IntegerField(default=20)
    question_rate_currency = models.IntegerField(default=5)
    status = models.CharField(max_length=50, default="")

    @property
    def player_name(self):
        """Return username of this player."""
        return self.user.username

    def update_player_stats(self, health: int = 0, dungeon_currency: int = 0, luck: float = 0):
        """Add values to stats of player."""
        self.current_hp += health
        if self.current_hp > self.max_hp:
            self.current_hp = self.max_hp
        self.dungeon_currency += dungeon_currency
        self.luck += luck
        self.save()

    def reset_stats(self):
        """Reset player's health to max and other stats to zero or empty."""
        self.current_hp = self.max_hp
        self.luck = BASE_LUCK
        self.dungeon_currency = 0
        self.status = ""
        self.save()

    def add_dungeon_currency(self):
        """Transfer coins from dungeon to main storage."""
        self.currency += self.dungeon_currency
        self.dungeon_currency = 0
        self.save()

    def set_activity(self, activity: str):
        """Set player activity."""
        self.activity = activity
        self.save()

    def check_death(self):
        """Check player's current health, if below zero, clear dungeon coins and inventory."""
        if self.current_hp <= 0:
            self.set_activity("index")
            self.reset_stats()
            Inventory.objects.get(player=self).clear_dungeon_inventory()
            self.save()
            return True
        return False


class Log(models.Model):
    """Log model for creating logs."""

    log_text = models.CharField(max_length=1000, default=";;;;;;;;;;")
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    log_questions = models.CharField(max_length=1000, default="")
    log_report_question = models.CharField(max_length=1000, default="")

    def split_log(self, log_type):
        """Return list form of a log in accordance to the type inputted."""
        if log_type == "text":
            return self.log_text.split(';')[:-1]
        if log_type == "question":
            return self.log_questions.split(';')[:-1]
        return self.log_report_question.split(';')[:-1]

    def clear_log(self):
        """Clear log to be empty."""
        self.log_text = ";;;;;;;;;;"
        self.save()

    def clear_question(self):
        """Clear seen questions to be none."""
        self.log_questions = ""
        self.save()

    def add_log(self, text):
        """Add new player action log."""
        list_log = self.log_text.split(';')
        del (list_log[0])
        self.log_text = ";".join(list_log)
        self.log_text += f"{text};"
        self.save()

    def add_question(self, question_id: str):
        """Add seen question id to log."""
        self.log_questions += f"{question_id};"
        if len(self.split_log('question')) > 100:
            self.clear_question()
        self.save()

    def remove_question(self, question_id: str):
        """Remove seen_question id from log."""
        seen_question = self.split_log("question")
        if question_id in seen_question:
            seen_question.remove(question_id)
            self.log_questions = f"{';'.join(seen_question)}" + ";"
        self.save()

    def add_report_question(self, question_id: int):
        """Add player's reported question to log."""
        if str(question_id) not in self.split_log("report"):
            self.log_report_question += f"{question_id};"
        self.save()

    def __str__(self):
        """Return Log string."""
        return self.log_text


class Inventory(models.Model):
    """Inventory model for creating inventory."""

    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    player_inventory = models.CharField(max_length=1000, default="")
    dungeon_inventory = models.CharField(max_length=1000, default="")
    max_inventory = models.IntegerField(default=3)
    question_template = models.CharField(max_length=1000, default="")

    def get_inventory(self, inventory_type):
        """Return dict of inventory."""
        dict_item = {}
        if inventory_type == "player":
            inventory = self.player_inventory.split(';')[:-1]
        else:
            inventory = self.dungeon_inventory.split(';')[:-1]
        for item in inventory:
            item_list = item.split(":")
            dict_item[int(item_list[0])] = int(item_list[1])
        return dict_item

    def update_inventory(self, item: dict, inventory_type):
        """Update item into inventory."""
        inventory = ""
        for key, val in item.items():
            if val > 0:
                inventory += f"{key}:{val};"
        if inventory_type == "player":
            self.player_inventory = inventory
        else:
            self.dungeon_inventory = inventory
        self.save()

    def clear_dungeon_inventory(self):
        """Clear dungeon inventory."""
        self.dungeon_inventory = ""
        self.save()

    def reset_inventory(self):
        """Move items from dungeon inventory to player inventory."""
        p_inventory = self.get_inventory("player")
        d_inventory = self.get_inventory("dungeon")
        for item, amount in d_inventory.items():
            if item in p_inventory:
                p_inventory[item] += amount
            else:
                p_inventory[item] = amount
        self.update_inventory(p_inventory, "player")
        self.clear_dungeon_inventory()

    def get_templates(self):
        """Return dict of player templates."""
        owned = {}
        for value in self.question_template.split(';')[:-1]:
            value = value.split(":")
            owned[int(value[0])] = int(value[1])
        return owned

    def update_templates(self, items: dict):
        """Update templates into inventory."""
        item_string = ""
        for key, value in items.items():
            if value > 0:
                item_string += f"{key}:{value};"
        self.question_template = item_string
        self.save()

qa_rpg/templates/qa_rpg/battle.html
<!doctype html>
{% load static %}
{% load tailwind_tags %}
<head>
{% tailwind_css %}
</head>
<title> Battle </title>

<body class="text-white font-serif bg-no-repeat bg-cover w-screen h-screen "
  style="background-image: url('https://assets.dicebreaker.com/dungeons-and-dragons-players-handbook-art-8png.jpg/BROK/resize/1920x1920%3E/format/jpg/quality/80/dungeons-and-dragons-players-handbook-art-8png.jpg;">

<div class="flex">
  <div class="m-8 p-4">
    <div class="h-20 w-[17rem] box-border bg-black bg-opacity-50 border-gray-600  border-2">
      <div class="text-pink-50 text-3xl pl-2 pt-1">
        HP: {{ player.current_hp }} / {{ player.max_hp }}<br>
          <a> Current coins: {{ player.dungeon_currency }} </a>
      </div>
    </div>
    <div class="h-15 w-[17rem] box-border bg-black bg-opacity-50 border-gray-600  border-2">
        <div class="text-white text-3xl pl-2 pt-1">
            {% if status %}
                {{ status }}
            {% else %}
                No item applied.
            {% endif%}
        </div>
    </div>
  </div>

  <div class="text-white text-3xl pl-2 pt-1 m-8 bg-black bg-opacity-50 border-gray-600 border-2">
    <form method="post" action="{% url 'qa_rpg:item' %}">
        {% csrf_token %}

        <label for="item" class="p-2">Select an item to use:</label>
            <div class="text-black text-3xl pl-2 pt-1">
            <select name="item" id="item" aria-readonly="true" required>
                <option value="">--Choose an item--</option>
                {% for key, value in items.items %}
                    <option value="{{ value.0 }}" title="{{ value.2 }}&#13;{{ value.3 }}">{{ key }}: {{ value.1 }}</option>
                {% endfor %}
            </select>
            </div>
        <div class="py-2 px-2">
            {% if status %}
                <button type="submit" class="bg-red bg-opacity-50 border-gray-600 border-2 pl-2 pt-1 pb-1 pr-2" disabled>Use item</button>
            {% else %}
                <button type="submit" class="bg-black bg-opacity-50 border-gray-600 border-2 hover:bg-green-700 duration-300 pl-2 pt-1 pb-1 pr-2">Use item</button>
            {% endif %}
        </div>
    </form>
  </div>
</div>

<form action="{% url 'qa_rpg:check' question.id %}" method="post">
{% csrf_token %}

    <div class="flex justify-center items-center py-4">
        <div class="bg-black bg-opacity-70 border-gray-600 border-2 w-3/4 h-28 justify-center items-center">
            <h1 class="p-2 text-3xl">
                {% if question.damage > 30 %}
                    <a class="text-red-700">(Hard)</a>
                {% elif question.damage > 25%}
                    <a class="text-orange-700">(Medium)</a>
                {% else %}
                    <a class="text-yellow-500">(Easy)</a>
                {% endif %}
                {{ question.question_text }}
            </h1>
        </div>
    </div>
    {% if messages %}
        {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
        <div class="flex item-center grid justify-center">
            {% if message.level == 40 %}
                <p class="text-red-700 text-3xl bg-black bg-opacity-80 border-gray-600 border-2 p-4"><strong>{{ message }}</strong></p>
            {% else %}
                <p class="text-green-600 text-3xl bg-black bg-opacity-80 border-gray-600 border-2 p-4"><strong>{{ message }}</strong></p>
            {% endif %}
        </div>
        {% endfor %}
    {% endif %}

<div class="flex">
    <div class="flex item-center grid justify-left py-4 w-[45rem] h-64 ml-48">
    {% for choice in question.choice_set.all %}
        <div class="my-2">
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" class="peer checked:bg-opacity-80">
            <label class="text-2xl bg-black bg-opacity-50 border-gray-600 border-2 hover:bg-opacity-80 pl-2 pt-1 pb-1 pr-2 peer-checked:bg-opacity-80" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        </div>
    {% endfor %}
    </div>


    <div class="flex justify-center item-center gap-4 ml-20 mt-20">
        <p>
            <button type="submit" class="text-5xl bg-black bg-opacity-50 border-gray-600 border-2 hover:bg-green-700 duration-300 pl-2 pt-1 pb-1 pr-2">Fight</button>
        </p>

        <div>
            <p>
                <button type="submit" class="text-5xl bg-black bg-opacity-50 border-gray-600 border-2 hover:bg-red-500 duration-300 pl-2 pt-1 pb-1 pr-2" formaction="{% url 'qa_rpg:run_away' question.id %}">Run Away</button>
            </p>
        </div>
    </div>
</div>
    <div class="absolute top-0 right-0 my-10 mx-10 py-2 text-2xl" >
        <div class="py-2">
            <input type="radio" name="option" id="not select" value="not selected" checked>
            <label for="not select" class="bg-black bg-opacity-50 border-gray-600 border-2 hover:text-blue-500 pl-2 pt-1 pb-1 pr-2" >Not selected</label><br>
        </div>
        <div class="py-2">
            <input type="radio" name="option" id="report" value="report">
            <label for="report" class="bg-black bg-opacity-50 border-gray-600 border-2 hover:text-red-500 pl-2 pt-1 pb-1 pr-2">Report</label><br>
        </div>

        <div class="py-2">
            <input type="radio" name="option" id="commend" value="commend">
            <label for="commend" class="bg-black bg-opacity-50 border-gray-600 border-2 hover:text-green-500 pl-2 pt-1 pb-1 pr-2">Commend</label><br>
        </div>
    </div>
</form>

</body>

qa_rpg/templates/qa_rpg/index.html
<!doctype html>
{% load static %}
{% load tailwind_tags %}
<head>
{% tailwind_css %}
</head>
<title> Hub </title>

<body class="text-white font-serif bg-no-repeat bg-cover w-screen h-screen "
  style="background-image: url('https://d.wattpad.com/story_parts/632993320/images/1555c78f7608fede446379137457.jpg');">
  <div class="m-8 p-4">
    <div class="h-25 w-[17rem] box-border bg-black bg-opacity-50 border-gray-600  border-2">
      <div class="text-pink-50 text-3xl pl-2 pt-1">
        <a> Coins: {{ player.currency }} </a> </br>
      </div>
    </div>
  </div>
  {% if messages %}
    {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
            <div class="ml-8 my-7 p-4">
                <div>
                    <div>
                    {% if message.level == 40 %}
                        <p class="text-red-600 text-center text-2xl bg-black bg-opacity-50 border-gray-600 border-2 pl-2 pt-1 pb-1 pr-2"><strong>{{ message }}</strong></p>
                    {% else %}
                        <p class="text-green-600 text-center text-2xl bg-black bg-opacity-50 border-gray-600 border-2 pl-2 pt-1 pb-1 pr-2"><strong>{{ message }}</strong></p>
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
  {% endif %}

  <div class="ml-8 my-7 p-4">
      <div class="h-25 w-60 box-border bg-black bg-opacity-50 border-gray-600  border-2">
          <div class="text-pink-50 text-3xl ">
                <a href="{% url 'qa_rpg:select_dg' %}"><button class=" h-25 w-60 bg-Neutral-900 hover:bg-red-900 duration-300" type="button">dungeon</button></a>
          </div>
      </div>
  </div>
  <div class="ml-8 my-7 p-4">
      <div class="h-25 w-60 box-border bg-black bg-opacity-50 border-gray-600  border-2">
          <div class="text-pink-50 text-3xl ">
                <a href="{% url 'qa_rpg:shop' %}"><button class=" h-25 w-60 bg-Neutral-900 hover:bg-red-900 duration-300" type="button">shop</button></a>
          </div>
      </div>
  </div>
<div class="ml-8 my-7 p-4">
      <div class="h-25 w-60 box-border bg-black bg-opacity-50 border-gray-600  border-2">
          <div class="text-pink-50 text-3xl ">
              <a href="{% url 'qa_rpg:template' %}"><button class=" h-25 w-60 bg-Neutral-900 hover:bg-red-900 duration-300" type="button">summon</button></a>
          </div>
      </div>
  </div>

<div class="ml-8 my-7 p-4">
      <div class="h-25 w-60 box-border bg-black bg-opacity-50 border-gray-600  border-2">
          <div class="text-pink-50 text-3xl ">
              <a href="{% url 'qa_rpg:profile' %}"><button class=" h-25 w-60 bg-Neutral-900 hover:bg-red-900 duration-300" type="button">profile</button></a>
          </div>
      </div>
  </div>
  <div class="ml-8 my-7 p-4">
      <div class="h-25 w-60 box-border bg-black bg-opacity-50 border-gray-600  border-2">
          <div class="text-pink-50 text-3xl ">
              <a href="https://github.com/QA-RPG/QA-RPG/wiki/How-to-play" target="_blank"><button class=" h-25 w-60 bg-Neutral-900 hover:bg-red-900 duration-300" type="button">How to play</button></a>
          </div>
      </div>
  </div>

<div class="absolute top-0 right-0 my-10 mx-10 py-2 text-2xl" >
        <div class="h-25 w-60 box-border bg-black bg-opacity-50 border-gray-600  border-2">
          <div class="text-pink-50 text-3xl ">
            <a href="{% url 'logout'%}"><button class="h-25 w-60 bg-Neutral-900 hover:bg-red-900 duration-300" type="button">Log out</button></a>
        </div>
      </div>
</div>

</body>

qa_rpg/templates/qa_rpg/profile.html
<!doctype html>
{% load static %}
{% load tailwind_tags %}
<head>
{% tailwind_css %}
</head>
<title> Profile </title>

<body class="text-white font-serif bg-no-repeat bg-cover w-screen h-screen"
  style="background-image: url('https://wallup.net/wp-content/uploads/2018/09/30/118900-fantasy-castle-room-dark.jpg');">
<div class="flex">
<div class="m-8 p-4 flex">
    <div class="h-50 box-border bg-black bg-opacity-50 border-gray-600  border-2">
      <div class="flex justify-center text-pink-50 text-5xl pl-2 pt-1 pb-1 pr-2">
        <a class="ml-11 mr-11 mt-14">{{ player.player_name }}</a><br>
      </div>
    </div>
    <div class="h-50 box-border bg-black bg-opacity-50 border-gray-600  border-2">
        <label class="bg-black bg-opacity-50 border-gray-600 border-2 pl-2 pb-1 pr-2 text-3xl ">Player Stats</label>
        <br>
        <div class="flex mt-3 justify-between px-3">
            <div class="text-3xl">
                Awaken Level: <br>
                Max HP: <br>
                Coin: <br>
                Total Monsters: <br>
            </div>
            <div class="flex text-3xl text-right pl-5">
                {{player.awake}}<br>
                {{ player.max_hp }}<br>
                {{player.currency}}<br>
                {{questions.count}}
            </div>
        </div>
    </div>
  </div>
    <div class="mt-28">
        <div class="h-25 w-60 box-border bg-black bg-opacity-50 border-gray-600  border-2">
          <div class="text-pink-50 text-3xl ">
                <a href="{% url 'qa_rpg:upgrade' %}"><button class=" h-25 w-60 bg-Neutral-900 hover:bg-blue-700 duration-300" type="button">Upgrade</button></a>
          </div>
      </div>
</div>
</div>

<div class="flex ml-8 mr-8 mb-8 p-4">
    <div class="h-80 w-1/2 box-border bg-black bg-opacity-50 border-gray-600  border-2 text-2xl">

        <label class="bg-black bg-opacity-50 border-gray-600 border-2 pl-2 pb-1 pr-2 text-3xl">Monsters</label>
        <div class="mt-3 px-2">
            <div class="h-64 overflow-auto">
        {% if questions %}
            <ul class="list-disc">
            {% for question in questions %}
                <form action="{% url 'qa_rpg:claim' question.id %}" method="post">
                    {% csrf_token %}
                    <div class="w-auto flex flex-col bg-black bg-opacity-50 border-gray-600 border-2 pl-2 pb-1 pr-2 mt-3 sticky">
                <li>{{ question.question_text }} <br>
                    {{question.currency}}/{{question.max_currency}}  <button type="submit" class="bg-black bg-opacity-50 hover:text-yellow-500 border-gray-600 border-2 pl-2 pr-2">Claim</button>
                    {% if not question.enable %}
                    <a class="text-red-600">Your monsters are imprisoned by GM.</a>
                    {% endif %}
                    <br></li>
                    </div>
                    </form>
            {% endfor %}
            </ul>

        {% else %}
            <p>You haven't summoned any monsters.</p>
        {% endif %}
            </div>
        </div>
    </div>
    <div class="h-80 w-1/2 box-border bg-black bg-opacity-50 border-gray-600  border-2 text-2xl">
        <div class="flex justify-center">
        <div class="w-full bg-black bg-opacity-50 hover:text-red-600 border-gray-600 border-2 pl-2 pb-1 pr-2 text-3xl text-center">
         <form action="{% url 'qa_rpg:select' %}" method="post">
            {% csrf_token %}
             <input type="hidden" name="select" value="item">
                 <button type="submit" >Items Inventory</button>
         </form>
            </div>
        <div class="w-full bg-black bg-opacity-50 hover:text-red-600 border-gray-600 border-2 pl-2 pb-1 pr-2 text-3xl text-center">
         <form action="{% url 'qa_rpg:select' %}" method="post">
            {% csrf_token %}
             <input type="hidden" name="select" value="template">
            <button type="submit">Templates Inventory</button>
         </form>
        </div>
        </div>
        <div class="mt-3 px-2">
            <div class="h-64 overflow-auto">

                {% if check %}
                {% if inventory %}
                    <ul class="list-disc">
                    {% for item in inventory %}
                            <div class="w-auto flex flex-col bg-black bg-opacity-50 border-gray-600 border-2 pl-2 pb-1 pr-2 mt-3 sticky">
                            <span title="{{ item.2 }}&#13;{{ item.3 }}">
                             <li>{{ item.0 }} <br>
                             </span>
                                In inventory: {{ item.1 }}
                                <br></li>
                            </div>
                    {% endfor %}
                    </ul>

                {% else %}
                    <p>You don't have any item.</p>
                {% endif %}
                {% else %}
                {% if template %}
                <ul class="list-disc">
                {% for key, val in template.items %}
                        <div class="w-auto flex flex-col bg-black bg-opacity-50 border-gray-600 border-2 pl-2 pb-1 pr-2 mt-3 sticky">
                         <li>{{ key }} <br>
                            In inventory: {{val.1}}
                            <br></li>
                        </div>
                {% endfor %}
                </ul>

            {% else %}
                <p>You don't have any template.</p>
            {% endif %}
            {% endif %}
                </div>

            </div>
        </div>
    </div>
</div>
<div class="ml-[3.1rem]">
      <div class="h-25 w-60 box-border bg-black bg-opacity-50 border-gray-600  border-2">
          <div class="text-pink-50 text-3xl ">
                <a href="{% url 'qa_rpg:index' %}"><button class=" h-25 w-60 bg-Neutral-900 hover:bg-red-900 duration-300" type="button">Back</button></a>
          </div>
      </div>
  </div>
</body>

qa_rpg/templates/qa_rpg/treasure.html
<!doctype html>
{% load static %}
{% load tailwind_tags %}
<head>
    {% tailwind_css %}
</head>
<title> Treasure </title>

<body class="text-white font-serif bg-no-repeat bg-cover w-screen h-screen"
  style="background-image: url('https://wallpaper.dog/large/10948486.jpg'); color: white;">
  <div class="m-8 p-4">
    <div class="h-20 w-[17rem] box-border bg-black bg-opacity-50 border-gray-600  border-2">
      <div class="text-pink-50 text-3xl pl-2 pt-1">
        HP: {{ player.current_hp }} / {{ player.max_hp }}
        <br> <a> Current coins: {{ player.dungeon_currency }} </a> </br>
      </div>
    </div>
  </div>


<form action="{% url 'qa_rpg:treasure_action' %}" method="post">
{% csrf_token %}
    <div class="flex justify-center item-center gap-4 mt-96">
        <input type="hidden" name="action" value="pick up" />
        <p>
            <button type="submit" class="text-5xl bg-black bg-opacity-50 border-gray-600 border-2 hover:bg-green-700 duration-300 pl-2 pt-1 pb-1 pr-2">Open</button>
        </p>

</form>

<form action="{% url 'qa_rpg:treasure_action' %}" method="post">
        {% csrf_token %}
            <div>
        <input type="hidden" name="action" value="walk" />
        <p>
            <button type="submit" class="text-5xl bg-black bg-opacity-50 border-gray-600 border-2 hover:bg-red-500 duration-300 pl-2 pt-1 pb-1 pr-2">Walk Away</button>
        </p>
            </div>
        </form>
    </div>
</body>